#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : smmap
Version  : 3.0.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/94/a5/8a3453f924f7fe1ce899289f13a325708ede9d86144ba2017332735ec3a8/smmap-3.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/94/a5/8a3453f924f7fe1ce899289f13a325708ede9d86144ba2017332735ec3a8/smmap-3.0.1.tar.gz
Summary  : A pure Python implementation of a sliding window memory map manager
Group    : Development/Tools
License  : BSD-3-Clause
Requires: smmap-license = %{version}-%{release}
Requires: smmap-python = %{version}-%{release}
Requires: smmap-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : nosexcover
BuildRequires : nosexcover-python

%description
## Motivation
When reading from many possibly large files in a fashion similar to random access, it is usually the fastest and most efficient to use memory maps.

%package license
Summary: license components for the smmap package.
Group: Default

%description license
license components for the smmap package.


%package python
Summary: python components for the smmap package.
Group: Default
Requires: smmap-python3 = %{version}-%{release}

%description python
python components for the smmap package.


%package python3
Summary: python3 components for the smmap package.
Group: Default
Requires: python3-core

%description python3
python3 components for the smmap package.


%prep
%setup -q -n smmap-3.0.1
cd %{_builddir}/smmap-3.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582587375
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/smmap
cp %{_builddir}/smmap-3.0.1/LICENSE %{buildroot}/usr/share/package-licenses/smmap/d8cf84b9448a6a681d4df50aaebb3e3447706249
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/smmap/d8cf84b9448a6a681d4df50aaebb3e3447706249

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
